# Generated by Django 4.2.1 on 2023-06-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_id', models.CharField(max_length=15)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.masterrelease')),
            ],
        ),
    ]
